### ISSUE TITLE
请问一下能够通过songmid一次性同时获取歌曲地址和歌词吗？

### ISSUE THREAD

**Issue by mebest100** [lunhui1994/node-music-api#2]
请问一下能够通过songmid一次性同时获取歌曲地址和歌词吗？
如果可以，那么命令参数是什么呢，谢谢

**Comment by lunhui1994** [comment]
https://api.zsfmyz.top/music/song?songmid=000aWBBQ2fMyBJ&guid=126548448&lyric=1  这样加上lyric=1参数就可以了。文档里有写的哦

**Comment by lunhui1994** [comment]
> 请问一下能够通过songmid一次性同时获取歌曲地址和歌词吗？
> 如果可以，那么命令参数是什么呢，谢谢

https://api.zsfmyz.top/music/song?songmid=000aWBBQ2fMyBJ&guid=126548448&lyric=1 这样加上lyric=1参数就可以了。文档里有写的哦

**Comment by mebest100** [comment]
好的，谢谢！
还有一个问题请教一下，就是通过接口并不是总能获取到正确的播放地址，有时候会获取到这样的无效地址https://ws.stream.qqmusic.qq.com，导致歌曲无法播放，请问这个问题怎么解决呢

**Comment by lunhui1994** [comment]
> 好的，谢谢！
> 还有一个问题请教一下，就是通过接口并不是总能获取到正确的播放地址，有时候会获取到这样的无效地址[https://ws.stream.qqmusic.qq.com，导致歌曲无法播放，请问这个问题怎么解决呢](https://ws.stream.qqmusic.qq.com%EF%BC%8C%E5%AF%BC%E8%87%B4%E6%AD%8C%E6%9B%B2%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%E5%91%A2)

这个问题的话原因是因为你请求的歌曲是属于VIP的歌曲吧，这种歌曲的播放地址的现在没法去获取的，就算以后获取了也不敢开放使用呀，我们并没有版权的，所以就是这个项目的目的就是给一些音乐类的项目测试用用。

**Comment by mebest100** [comment]
好的，明白了，我加了歌曲长度的过滤规则就好了，谢谢！
