### ISSUE TITLE
你好！音乐搜索列表能多加一个catZhida=1的查询参数吗，谢谢！

### ISSUE THREAD

**Issue by mebest100** [lunhui1994/node-music-api#3]
你好！ 音乐搜索列表能多加一个catZhida=1的参数吗，谢谢！
 
 https://api.zsfmyz.top/music/list?p=1&n=30&w=任然&catZhida=1

返回的数据格式像下面这样：

![image](https://user-images.githubusercontent.com/11530991/91822517-7dd4ad80-ec6a-11ea-9501-006d37517448.png)

因为目前用的是别人网站架的一个接口，但是那人很龌龊，不肯透漏接口源码来源（实际接口也不是他写的），用别人的接口到底还是不方便，看看您这边能不能加个功能，谢谢！

**Comment by lunhui1994** [comment]
> 你好！ 音乐搜索列表能多加一个catZhida=1的参数吗，谢谢！
> 
> [https://api.zsfmyz.top/music/list?p=1&n=30&w=任然&catZhida=1](https://api.zsfmyz.top/music/list?p=1&n=30&w=%E4%BB%BB%E7%84%B6&catZhida=1)
> 
> 返回的数据格式像下面这样：
> 
> ![image](https://user-images.githubusercontent.com/11530991/91822517-7dd4ad80-ec6a-11ea-9501-006d37517448.png)
> 
> 因为目前用的是别人网站架的一个接口，但是那人很龌龊，不肯透漏接口源码来源（实际接口也不是他写的），用别人的接口到底还是不方便，看看您这边能不能加个功能，谢谢！

这个参数是大概什么意思呢？

**Comment by mebest100** [comment]
这个我也说不清楚，你可以看看这个原生的请求（需要用jsonp做跨域处理），包含了zhida的返回数据，我个人的理解应该是按照关键字搜索出的歌手的相关信息，跟你那个list有所区别，zhida的信息更直接的反映了搜索的歌手的信息，包括了歌手名字，专辑中歌曲数量，歌手头像等等：

https://c.y.qq.com/soso/fcgi-bin/search_for_qq_cp?_=1599056258952&g_tk=5381&uin=1296538920&format=json&inCharset=utf-8&outCharset=utf-8&notice=0&platform=h5&needNewCode=1&g_tk_new_20200303=5381

![image](https://user-images.githubusercontent.com/11530991/91997089-49e1b100-ed6c-11ea-9abf-b71714281f8a.png)

**Comment by lunhui1994** [comment]
> 这个我也说不清楚，你可以看看这个原生的请求（需要用jsonp做跨域处理），包含了zhida的返回数据，我个人的理解应该是按照关键字搜索出的歌手的相关信息，跟你那个list有所区别，zhida的信息更直接的反映了搜索的歌手的信息，包括了歌手名字，专辑中歌曲数量，歌手头像等等：
> 
> https://c.y.qq.com/soso/fcgi-bin/search_for_qq_cp?_=1599056258952&g_tk=5381&uin=1296538920&format=json&inCharset=utf-8&outCharset=utf-8&notice=0&platform=h5&needNewCode=1&g_tk_new_20200303=5381
> 
> ![image](https://user-images.githubusercontent.com/11530991/91997089-49e1b100-ed6c-11ea-9abf-b71714281f8a.png)

有空的时候我看一下。最近有点忙，可能没啥子时间 。

**Comment by zRains** [comment]
这个应该是没问题的，通过原接口`https://c.y.qq.com/soso/fcgi-bin/client_search_cp?catZhida=1&n=10&w=周杰伦&format=json`可以获取你所说的详细信息，而且可以应用到歌曲上，不过给的好像是MV的相关信息，这就要看你怎么选择了。
```js
return new Promise((resolve, reject) => {
    musicInterface({
        method: 'get',
        url: apiUrl.searchUrl,
        params: params
    }).then(res => {
        res = JSON.parse(res.data.match(regExp.jsonpRegExp)[0]);
        let params = {
            curnum: res.data.song.curnum,
            curpage: res.data.song.curpage,
            zhida: res.data.zhida.zhida_singer || res.data.zhida.zhida_mv,
            list: []
        }
        for (let item of res.data.song.list) {
            params.list.push({
                songname: item.songname,
                singer: item.singer[0],
                albumname: item.albumname,
                songmid: item.songmid,
                albumimg: apiUrl.albumimgUrl + (item.albumid % 100) + '/300_albumpic_' + item.albumid + '_0.jpg'
            })
        }
        resolve(params);
    }, err => {
        reject(err);
    })
})
```
希望能帮到你:blush:
